CREATE TABLE `mkho_ctrans`.`m1_return` (
`subject` VARCHAR( 100 ) NOT NULL DEFAULT '0',
`datestamp` DATE NOT NULL DEFAULT '0000-00-00',
`timestamp` TIME NOT NULL DEFAULT '00:00:00',
`version` VARCHAR( 20 ) NOT NULL DEFAULT '',
`A1` INT( 5 ) NOT NULL DEFAULT '0',
`S2` INT( 5 ) NOT NULL DEFAULT '0',
`A2` INT( 5 ) NOT NULL DEFAULT '0',
`Re` INT( 5 ) NOT NULL DEFAULT '0',
`rt1` VARCHAR( 10 ) NOT NULL DEFAULT '',
`rt2` VARCHAR( 10 ) NOT NULL DEFAULT '',
`score` INT( 5 ) NOT NULL DEFAULT '0',
`round` INT( 5 ) NOT NULL DEFAULT '0',
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
KEY(`id`)
);

CREATE TABLE `mkho_ctrans`.`moral` (
`subject` VARCHAR( 100 ) NOT NULL DEFAULT '0',
`datestamp` DATE NOT NULL DEFAULT '0000-00-00',
`timestamp` TIME NOT NULL DEFAULT '00:00:00',
`version` VARCHAR( 20 ) NOT NULL DEFAULT '',
`moral1` INT( 20 ) NOT NULL DEFAULT '0',
`moral2` INT( 20 ) NOT NULL DEFAULT '0',
`moral3` INT( 20 ) NOT NULL DEFAULT '0',
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
KEY(`id`)
);

CREATE TABLE `mkho_ctrans`.`pur` (
`subject` VARCHAR( 100 ) NOT NULL DEFAULT '0',
`datestamp` DATE NOT NULL DEFAULT '0000-00-00',
`timestamp` TIME NOT NULL DEFAULT '00:00:00',
`version` VARCHAR( 20 ) NOT NULL DEFAULT '',
`pur1` INT( 20 ) NOT NULL DEFAULT '0',
`pur2` INT( 20 ) NOT NULL DEFAULT '0',
`pur3` INT( 20 ) NOT NULL DEFAULT '0',
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
KEY(`id`)
);

CREATE TABLE `mkho_ctrans`.`m1_demo` (
`subject` VARCHAR( 100 ) NOT NULL DEFAULT '0',
`datestamp` DATE NOT NULL DEFAULT '0000-00-00',
`timestamp` TIME NOT NULL DEFAULT '00:00:00',
`version` VARCHAR( 20 ) NOT NULL DEFAULT '',
`god` INT( 5 ) NOT NULL DEFAULT '0',
`soc` INT( 5 ) NOT NULL DEFAULT '0',
`fis` INT( 5 ) NOT NULL DEFAULT '0',
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
KEY(`id`)
);

CREATE TABLE `mkho_ctrans`.`crt` (
`subject` VARCHAR( 100 ) NOT NULL DEFAULT '0',
`datestamp` DATE NOT NULL DEFAULT '0000-00-00',
`timestamp` TIME NOT NULL DEFAULT '00:00:00',
`version` VARCHAR( 20 ) NOT NULL DEFAULT '',
`crt1` INT( 20 ) NOT NULL DEFAULT '0',
`crt2` INT( 20 ) NOT NULL DEFAULT '0',
`crt3` INT( 20 ) NOT NULL DEFAULT '0',
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
KEY(`id`)
);

CREATE TABLE `mkho_ctrans`.`discounting` (
`subject` VARCHAR( 100 ) NOT NULL DEFAULT '0',
`datestamp` DATE NOT NULL DEFAULT '0000-00-00',
`timestamp` TIME NOT NULL DEFAULT '00:00:00',
`version` VARCHAR( 20 ) NOT NULL DEFAULT '',
`d1` INT( 5 ) NOT NULL DEFAULT '0',
`d2` INT( 5 ) NOT NULL DEFAULT '0',
`d3` INT( 5 ) NOT NULL DEFAULT '0',
`d4` INT( 5 ) NOT NULL DEFAULT '0',
`d5` INT( 5 ) NOT NULL DEFAULT '0',
`d6` INT( 5 ) NOT NULL DEFAULT '0',
`d7` INT( 5 ) NOT NULL DEFAULT '0',
`d8` INT( 5 ) NOT NULL DEFAULT '0',
`d9` INT( 5 ) NOT NULL DEFAULT '0',
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
KEY(`id`)
);